sudo: required

cache:
  apt: true
  
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - git fetch origin master
  - git checkout master

script:
  - ./scripts/travis-entrypoint.sh
